;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=C:/Users/jackb/Downloads/Script/en
DestinationPath=Content/Localization/Game
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr
ManifestName=Game.manifest
ArchiveName=Game.archive
PortableObjectName=Game.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal

