;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Game
DestinationPath=C:/Users/jackb/Downloads/Script
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr
ManifestName=Game.manifest
ArchiveName=Game.archive
DialogueScriptName=GameDialogue.csv

[GatherTextStep0]
CommandletClass=ExportDialogueScript

